# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            skyzerotiger
tagline:          ''
description:      'Game & App Programmer'
url:              http://skyzerotiger.com
baseurl:          /

author:
  name:           'skyzerotiger'
  url:            https://skyzerotiger.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/skyzerotiger
