# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            skyzerotiger
tagline:          ''
description:      '프로그래머'
url:              https://skyzerotiger.com
baseurl:          https://skyzerotiger.com/

author:
  name:           'skyzerotiger'
  url:            https://skyzerotiger.com

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/skyzerotiger
