# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            skyzerotiger
tagline:          ''
description:      'Game & App Programmer'
url:              http://skyzerotiger.com
baseurl:          http://skyzerotiger.com

author:
  name:           'skyzerotiger'
  url:            https://skyzerotiger.com

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/skyzerotiger
